export { and } from "./and";
export { contains } from "./contains";
export { containsSimilarTo } from "./containsSimilarTo";
export { hasPart } from "./hasPart";
export { isAnything } from "./isAnything";
export { matches } from "./matches";
export { or } from "./or";
export { similarTo } from "./similarTo";
export { When } from "./When";
