name: Release From Main

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn lint
        env:
          CI: true

  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: yarn test:integration

  update-documentation:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn build
      - name: Generate documentation
        run: yarn doc
      - name: Commit updated documentation
        uses: EndBug/add-and-commit@v5
        with:
          message: "Update documentation"
          add: "**/doc/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: update-documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn --frozen-lockfile
      - run: yarn readme:copy
      - run: yarn build
        # Flag --no-verify-access is necessary to skip user and access validation due to third-party registry
        # Alternatively set command.publish.registry in root lerna.json
      - run: yarn lerna publish from-package --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
