name: On Push

on: [push]

jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Setup Node
#        uses: actions/setup-node@v1
#        with:
#          node-version: 12.x
#      - run: yarn
#      - run: yarn lint
#        env:
#          CI: true
#
#  build-and-test:
#    runs-on: ubuntu-latest
#    timeout-minutes: 30
#    steps:
#      - uses: actions/checkout@v1
#      - name: Setup Node
#        uses: actions/setup-node@v1
#        with:
#          node-version: 12.x
#      - run: yarn
#      - run: yarn build
#      - run: yarn test

  update-docs:
#    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn build
      - name: Update documentation
        uses: EndBug/add-and-commit@v5
        with:
          message: "Update documentation"
          add: "**/docs/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
